imports:
  - path: deployment.jinja

resources:
  - name: kubeflow-demo
    type: deployment.jinja
    properties:
      zone: asia-northeast1
      serviceAccountId: test-account-id
      serviceAccountDisplayName: test-account-id
