import os

from dotenv import load_dotenv

load_dotenv()

# Project
PROJECT_ID = os.getenv("PROJECT_ID")
REGION = os.getenv("REGION")

# Service Account
APP_SERVICE_ACCOUNT_ID = os.getenv("APP_SERVICE_ACCOUNT_ID")
APP_SERVICE_ACCOUNT = os.getenv("APP_SERVICE_ACCOUNT")

# Google Cloud Storage
BUCKET_NAME = os.getenv("BUCKET_NAME")
BUCKET_URI = os.getenv("BUCKET_URI")

# Vertex AI Platform
PROJECT_NAME = os.getenv("PROJECT_NAME")
PIPELINE_ROOT = os.getenv("PIPELINE_ROOT")
COMPILED_PIPELINE_JSON = os.getenv("COMPILED_PIPELINE_JSON")
PIPELINE_DISPLAY_NAME_SUFFIX = os.getenv("PIPELINE_DISPLAY_NAME_SUFFIX")

# TabularDatasetCreateOp
DATASET_DISPLAY_NAME = os.getenv("DATASET_DISPLAY_NAME")

# AutoMLTabularTrainingJobRunOp
TRAINING_DISPLAY_NAME = os.getenv("TRAINING_DISPLAY_NAME")
TRAINING_BUDGET_MILLI_NODE_HOURS = os.getenv("TRAINING_BUDGET_MILLI_NODE_HOURS")
TRAINING_PREDICTION_TYPE = os.getenv("TRAINING_PREDICTION_TYPE")
TRAINING_OPTIMIZATION_OBJECTIVE = os.getenv("TRAINING_OPTIMIZATION_OBJECTIVE")

# EndpointCreateOp
ENDPOINT_DISPLAY_NAME = os.getenv("ENDPOINT_DISPLAY_NAME")
API_ENDPOINT = os.getenv("API_ENDPOINT")

# ModelDeployOp
MODEL_DEPLOY_MACHINE_TYPE = os.getenv("MODEL_DEPLOY_MACHINE_TYPE")
MODEL_DEPLOY_MIN_REPLICA_COUNT = os.getenv("MODEL_DEPLOY_MIN_REPLICA_COUNT")
MODEL_DEPLOY_MAX_REPLICA_COUNT = os.getenv("MODEL_DEPLOY_MAX_REPLICA_COUNT")

# Data
CSV_DATA_SOURCE = os.getenv("CSV_DATA_SOURCE")
CSV_FILE_NAME = os.getenv("CSV_FILE_NAME")
GCS_CSV_PATH = os.getenv("GCS_CSV_PATH")
DATA_TABLE_SCHEME = os.getenv("DATA_TABLE_SCHEME")
